sigmoid

In [8]:
import numpy as np

def basic_sigmoid(x):

    s = 1 / (1 + np.exp(-x))

    return s

In [9]:
basic_sigmoid(1)

0.7310585786300049

In [10]:
import math

def math_sigmoid(x):

    s = 1 / (1 + math.exp(-x))

    return s

In [11]:
math_sigmoid(1)

0.7310585786300049

vectors

In [13]:
x = np.array([1,2,3])

In [14]:
x = x+3

In [15]:
x

array([4, 5, 6])

sigmoid derivative

In [17]:
#sigmoid derivative

def sigmoid_derivative(x):

    s = math_sigmoid(x)
    ds = s * (1 - s)

    return ds

In [18]:
sigmoid_derivative(1)

0.19661193324148185

In [19]:
sigmoid_derivative(2)

0.10499358540350662

image to vector

In [21]:
def imagetovector(image):

    v = image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)

    return v


In [22]:
image = np.array([[[0.6765, 0.2765],[0.4765, 5.2765],[0.9765, 0.5765]],
                  [[0.6765, 0.2765],[0.4765, 5.2765],[0.9765, 0.5765]],
                  [[0.6765, 0.2765],[0.4765, 5.2765],[0.9765, 0.5765]]]
                   )


In [23]:
print(str(imagetovector(image)))

[[0.6765]
 [0.2765]
 [0.4765]
 [5.2765]
 [0.9765]
 [0.5765]
 [0.6765]
 [0.2765]
 [0.4765]
 [5.2765]
 [0.9765]
 [0.5765]
 [0.6765]
 [0.2765]
 [0.4765]
 [5.2765]
 [0.9765]
 [0.5765]]


normalising data/ rows

In [24]:
def normalize(x):

    x_norm = np.linalg.norm(x, axis = 1, keepdims = True)
    x = x / x_norm

    return x

In [30]:
x1 = np.array([[0,1000,4], [2,6,4]])

In [31]:
normalize(x1)

array([[0.        , 0.999992  , 0.00399997],
       [0.26726124, 0.80178373, 0.53452248]])

softmax

In [33]:
def softmax(x):

    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis = 1, keepdims = True)
    s = x_exp / x_sum

    return s

In [34]:
softmax(x1)

<ipython-input-33-aeaa3fd819d8>:3: RuntimeWarning: overflow encountered in exp
  x_exp = np.exp(x)
<ipython-input-33-aeaa3fd819d8>:5: RuntimeWarning: invalid value encountered in divide
  s = x_exp / x_sum


array([[0.        ,        nan, 0.        ],
       [0.01587624, 0.86681333, 0.11731043]])

vectorization

In [36]:
import time
#dot product
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0, 9]
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 196
 ----- Computation time = 0.11087000000031821ms


In [38]:
# outer product
ticc = time.process_time() # Call the function and assign the result to ticc
outer = np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
tocc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(tocc - ticc)) + "ms")

dot = 196
 ----- Computation time = 1.5561169999998015ms
